### ISSUE TITLE
blog post about dependabot for custom GitHub registries

### ISSUE THREAD

**Issue by pavelzw** [pavelzw/blog#4]
The documentation is incomplete

**Comment by pavelzw** [comment]
```yml
# dependabot.yml
version: 2
registries:
  npm-gh:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.DEPENDABOT_NPM_PAT }}
  docker-ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: _unused
    password: ${{ secrets.DEPENDABOT_NPM_PAT }}
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.PAVEL_DEPENDABOT }}
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    registries:
      - docker-ghcr
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    registries:
      - github
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    registries:
      - npm-gh
    groups:
      dependencies:
        patterns:
          - "*"
```

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

with a `.npmrc` in `frontend/` containing
```
@company-scope:registry=https://npm.pkg.github.com
```
